GET http://localhost:3001/api/engineer-manage/get-engineers

###

GET http://localhost:3001/api/project-manage/get-projects

###

POST http://localhost:3001/api/engineer-manage/add-engineer HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json

{
    "emp_id": "asjdasdh2323847234",
    "status":"ONGOING",
    "description":"THis is new project",
    "project_id":"62578612fc86c5d586232d29"
}   